/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __HELLO_BUFFER_CONFIG_BPF_SKEL_H__
#define __HELLO_BUFFER_CONFIG_BPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

#define BPF_SKEL_SUPPORTS_MAP_AUTO_ATTACH 1

struct hello_buffer_config_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *output;
		struct bpf_map *my_config;
		struct bpf_map *data;
		struct bpf_map *kconfig;
	} maps;
	struct {
		struct bpf_program *hello;
	} progs;
	struct {
		struct bpf_link *hello;
	} links;
	struct hello_buffer_config_bpf__data {
		char message[12];
	} *data;
	struct hello_buffer_config_bpf__kconfig {
		_Bool LINUX_HAS_SYSCALL_WRAPPER;
	} *kconfig;

#ifdef __cplusplus
	static inline struct hello_buffer_config_bpf *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct hello_buffer_config_bpf *open_and_load();
	static inline int load(struct hello_buffer_config_bpf *skel);
	static inline int attach(struct hello_buffer_config_bpf *skel);
	static inline void detach(struct hello_buffer_config_bpf *skel);
	static inline void destroy(struct hello_buffer_config_bpf *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
hello_buffer_config_bpf__destroy(struct hello_buffer_config_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
hello_buffer_config_bpf__create_skeleton(struct hello_buffer_config_bpf *obj);

static inline struct hello_buffer_config_bpf *
hello_buffer_config_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct hello_buffer_config_bpf *obj;
	int err;

	obj = (struct hello_buffer_config_bpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = hello_buffer_config_bpf__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	hello_buffer_config_bpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct hello_buffer_config_bpf *
hello_buffer_config_bpf__open(void)
{
	return hello_buffer_config_bpf__open_opts(NULL);
}

static inline int
hello_buffer_config_bpf__load(struct hello_buffer_config_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct hello_buffer_config_bpf *
hello_buffer_config_bpf__open_and_load(void)
{
	struct hello_buffer_config_bpf *obj;
	int err;

	obj = hello_buffer_config_bpf__open();
	if (!obj)
		return NULL;
	err = hello_buffer_config_bpf__load(obj);
	if (err) {
		hello_buffer_config_bpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
hello_buffer_config_bpf__attach(struct hello_buffer_config_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
hello_buffer_config_bpf__detach(struct hello_buffer_config_bpf *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *hello_buffer_config_bpf__elf_bytes(size_t *sz);

static inline int
hello_buffer_config_bpf__create_skeleton(struct hello_buffer_config_bpf *obj)
{
	struct bpf_object_skeleton *s;
	struct bpf_map_skeleton *map __attribute__((unused));
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "hello_buffer_config_bpf";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 4;
	s->map_skel_sz = 24;
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt,
			sizeof(*s->maps) > 24 ? sizeof(*s->maps) : 24);
	if (!s->maps) {
		err = -ENOMEM;
		goto err;
	}

	map = (struct bpf_map_skeleton *)((char *)s->maps + 0 * s->map_skel_sz);
	map->name = "output";
	map->map = &obj->maps.output;

	map = (struct bpf_map_skeleton *)((char *)s->maps + 1 * s->map_skel_sz);
	map->name = "my_config";
	map->map = &obj->maps.my_config;

	map = (struct bpf_map_skeleton *)((char *)s->maps + 2 * s->map_skel_sz);
	map->name = "hello_bu.data";
	map->map = &obj->maps.data;
	map->mmaped = (void **)&obj->data;

	map = (struct bpf_map_skeleton *)((char *)s->maps + 3 * s->map_skel_sz);
	map->name = "hello_b.kconfig";
	map->map = &obj->maps.kconfig;
	map->mmaped = (void **)&obj->kconfig;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs) {
		err = -ENOMEM;
		goto err;
	}

	s->progs[0].name = "hello";
	s->progs[0].prog = &obj->progs.hello;
	s->progs[0].link = &obj->links.hello;

	s->data = hello_buffer_config_bpf__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *hello_buffer_config_bpf__elf_bytes(size_t *sz)
{
	static const char data[] __attribute__((__aligned__(8))) = "\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\xb8\x13\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x0e\0\
\x01\0\xbf\x16\0\0\0\0\0\0\x18\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x71\x11\0\0\0\0\
\0\0\x15\x01\x2b\0\0\0\0\0\x79\x63\0\0\0\0\0\0\xb7\x01\0\0\0\0\0\0\x0f\x13\0\0\
\0\0\0\0\xbf\xa1\0\0\0\0\0\0\x07\x01\0\0\xc8\xff\xff\xff\xb7\x02\0\0\x08\0\0\0\
\x85\0\0\0\x71\0\0\0\x79\xa7\xc8\xff\0\0\0\0\xb7\x01\0\0\0\0\0\0\x63\x1a\xf4\
\xff\0\0\0\0\x63\x1a\xf0\xff\0\0\0\0\x63\x1a\xec\xff\0\0\0\0\x63\x1a\xe8\xff\0\
\0\0\0\x63\x1a\xe4\xff\0\0\0\0\x63\x1a\xe0\xff\0\0\0\0\x63\x1a\xdc\xff\0\0\0\0\
\x63\x1a\xd8\xff\0\0\0\0\x63\x1a\xd4\xff\0\0\0\0\x63\x1a\xd0\xff\0\0\0\0\x63\
\x1a\xf8\xff\0\0\0\0\x85\0\0\0\x0e\0\0\0\x77\0\0\0\x20\0\0\0\x63\x0a\xc8\xff\0\
\0\0\0\x85\0\0\0\x0f\0\0\0\x63\x0a\xcc\xff\0\0\0\0\xbf\xa1\0\0\0\0\0\0\x07\x01\
\0\0\xd0\xff\xff\xff\xb7\x02\0\0\x10\0\0\0\x85\0\0\0\x10\0\0\0\xbf\xa1\0\0\0\0\
\0\0\x07\x01\0\0\xec\xff\xff\xff\xb7\x02\0\0\x10\0\0\0\xbf\x73\0\0\0\0\0\0\x85\
\0\0\0\x72\0\0\0\xbf\xa2\0\0\0\0\0\0\x07\x02\0\0\xcc\xff\xff\xff\x18\x01\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x85\0\0\0\x01\0\0\0\x18\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x15\0\x2c\0\0\0\0\0\x05\0\x2a\0\0\0\0\0\xb7\x01\0\0\0\0\0\0\xbf\x63\0\0\0\0\0\
\0\x0f\x13\0\0\0\0\0\0\xbf\xa1\0\0\0\0\0\0\x07\x01\0\0\xc8\xff\xff\xff\xb7\x02\
\0\0\x08\0\0\0\x85\0\0\0\x71\0\0\0\x79\xa7\xc8\xff\0\0\0\0\xb7\x01\0\0\0\0\0\0\
\x63\x1a\xf4\xff\0\0\0\0\x63\x1a\xf0\xff\0\0\0\0\x63\x1a\xec\xff\0\0\0\0\x63\
\x1a\xe8\xff\0\0\0\0\x63\x1a\xe4\xff\0\0\0\0\x63\x1a\xe0\xff\0\0\0\0\x63\x1a\
\xdc\xff\0\0\0\0\x63\x1a\xd8\xff\0\0\0\0\x63\x1a\xd4\xff\0\0\0\0\x63\x1a\xd0\
\xff\0\0\0\0\x63\x1a\xf8\xff\0\0\0\0\x85\0\0\0\x0e\0\0\0\x77\0\0\0\x20\0\0\0\
\x63\x0a\xc8\xff\0\0\0\0\x85\0\0\0\x0f\0\0\0\x63\x0a\xcc\xff\0\0\0\0\xbf\xa1\0\
\0\0\0\0\0\x07\x01\0\0\xd0\xff\xff\xff\xb7\x02\0\0\x10\0\0\0\x85\0\0\0\x10\0\0\
\0\xbf\xa1\0\0\0\0\0\0\x07\x01\0\0\xec\xff\xff\xff\xb7\x02\0\0\x10\0\0\0\xbf\
\x73\0\0\0\0\0\0\x85\0\0\0\x72\0\0\0\xbf\xa2\0\0\0\0\0\0\x07\x02\0\0\xcc\xff\
\xff\xff\x18\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x85\0\0\0\x01\0\0\0\x18\x03\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x15\0\x01\0\0\0\0\0\xbf\x03\0\0\0\0\0\0\xbf\xa1\0\0\0\0\
\0\0\x07\x01\0\0\xe0\xff\xff\xff\xb7\x02\0\0\x0c\0\0\0\x85\0\0\0\x71\0\0\0\xbf\
\xa4\0\0\0\0\0\0\x07\x04\0\0\xc8\xff\xff\xff\xbf\x61\0\0\0\0\0\0\x18\x02\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x18\x03\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\xb7\x05\0\0\
\x34\0\0\0\x85\0\0\0\x19\0\0\0\xb7\0\0\0\0\0\0\0\x95\0\0\0\0\0\0\0\x48\x65\x6c\
\x6c\x6f\x20\x57\x6f\x72\x6c\x64\0\x44\x75\x61\x6c\x20\x42\x53\x44\x2f\x47\x50\
\x4c\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x9f\xeb\x01\0\x18\0\0\0\
\0\0\0\0\x4c\x04\0\0\x4c\x04\0\0\xb8\x03\0\0\0\0\0\0\0\0\0\x02\x03\0\0\0\x01\0\
\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\
\0\0\x04\0\0\0\x05\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\0\x03\0\0\x04\x18\
\0\0\0\x19\0\0\0\x01\0\0\0\0\0\0\0\x1e\0\0\0\x01\0\0\0\x40\0\0\0\x27\0\0\0\x01\
\0\0\0\x80\0\0\0\x32\0\0\0\0\0\0\x0e\x05\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\x02\x08\
\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\
\x02\x0a\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\0\x28\0\0\0\0\0\0\
\0\0\0\x02\x0c\0\0\0\x39\0\0\0\0\0\0\x08\x0d\0\0\0\x3d\0\0\0\0\0\0\x08\x0e\0\0\
\0\x43\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\x02\x10\0\0\0\x50\0\0\
\0\x01\0\0\x04\x0c\0\0\0\x5b\0\0\0\x12\0\0\0\0\0\0\0\x63\0\0\0\0\0\0\x01\x01\0\
\0\0\x08\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x11\0\0\0\x04\0\0\0\x0c\0\0\0\0\0\0\
\0\x04\0\0\x04\x20\0\0\0\x19\0\0\0\x07\0\0\0\0\0\0\0\x68\0\0\0\x09\0\0\0\x40\0\
\0\0\x74\0\0\0\x0b\0\0\0\x80\0\0\0\x78\0\0\0\x0f\0\0\0\xc0\0\0\0\x7e\0\0\0\0\0\
\0\x0e\x13\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\x02\x16\0\0\0\x88\0\0\0\x09\0\0\x04\
\x50\x01\0\0\0\0\0\0\x17\0\0\0\0\0\0\0\x90\0\0\0\x1d\0\0\0\x80\x08\0\0\x98\0\0\
\0\x1f\0\0\0\xc0\x08\0\0\xa2\0\0\0\x0c\0\0\0\xe0\x08\0\0\xaa\0\0\0\x1d\0\0\0\0\
\x09\0\0\xb5\0\0\0\x1d\0\0\0\x40\x09\0\0\xbe\0\0\0\x21\0\0\0\x80\x09\0\0\xc9\0\
\0\0\x1d\0\0\0\0\x0a\0\0\xda\0\0\0\x1d\0\0\0\x40\x0a\0\0\0\0\0\0\x02\0\0\x05\
\x10\x01\0\0\xe3\0\0\0\x18\0\0\0\0\0\0\0\0\0\0\0\x1c\0\0\0\0\0\0\0\xed\0\0\0\
\x04\0\0\x04\x10\x01\0\0\xfa\0\0\0\x1b\0\0\0\0\0\0\0\xff\0\0\0\x19\0\0\0\xc0\
\x07\0\0\x02\x01\0\0\x19\0\0\0\0\x08\0\0\x05\x01\0\0\x19\0\0\0\x40\x08\0\0\x0c\
\x01\0\0\0\0\0\x08\x1a\0\0\0\x12\x01\0\0\0\0\0\x01\x08\0\0\0\x40\0\0\0\0\0\0\0\
\0\0\0\x03\0\0\0\0\x19\0\0\0\x04\0\0\0\x1f\0\0\0\0\0\0\0\x04\0\0\x04\x10\x01\0\
\0\xfa\0\0\0\x1e\0\0\0\0\0\0\0\xff\0\0\0\x1d\0\0\0\xc0\x07\0\0\x02\x01\0\0\x1d\
\0\0\0\0\x08\0\0\x05\x01\0\0\x1d\0\0\0\x40\x08\0\0\x25\x01\0\0\0\0\0\x08\x19\0\
\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x1d\0\0\0\x04\0\0\0\x1f\0\0\0\x29\x01\0\0\0\0\0\
\x08\x20\0\0\0\x2d\x01\0\0\0\0\0\x08\x02\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x1d\0\
\0\0\x04\0\0\0\x02\0\0\0\0\0\0\0\x01\0\0\x0d\x02\0\0\0\x33\x01\0\0\x15\0\0\0\
\x37\x01\0\0\x01\0\0\x0c\x22\0\0\0\xc6\x01\0\0\x01\0\0\x04\x08\0\0\0\x90\0\0\0\
\x25\0\0\0\0\0\0\0\xd6\x01\0\0\0\0\0\x01\x08\0\0\0\x40\0\0\0\x5b\0\0\0\0\0\0\
\x0e\x12\0\0\0\x01\0\0\0\x73\x03\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\x04\x79\x03\0\
\0\0\0\0\x0e\x27\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x11\0\0\0\x04\0\0\0\
\x0d\0\0\0\x93\x03\0\0\0\0\0\x0e\x29\0\0\0\x01\0\0\0\x9b\x03\0\0\x01\0\0\x0f\0\
\0\0\0\x26\0\0\0\0\0\0\0\x0c\0\0\0\xa1\x03\0\0\x01\0\0\x0f\0\0\0\0\x28\0\0\0\0\
\0\0\0\x01\0\0\0\xaa\x03\0\0\x02\0\0\x0f\0\0\0\0\x06\0\0\0\0\0\0\0\x18\0\0\0\
\x14\0\0\0\0\0\0\0\x20\0\0\0\xb0\x03\0\0\x01\0\0\x0f\0\0\0\0\x2a\0\0\0\0\0\0\0\
\x0d\0\0\0\0\x69\x6e\x74\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\x49\x5a\x45\x5f\
\x54\x59\x50\x45\x5f\x5f\0\x74\x79\x70\x65\0\x6b\x65\x79\x5f\x73\x69\x7a\x65\0\
\x76\x61\x6c\x75\x65\x5f\x73\x69\x7a\x65\0\x6f\x75\x74\x70\x75\x74\0\x75\x33\
\x32\0\x5f\x5f\x75\x33\x32\0\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x69\x6e\x74\0\
\x75\x73\x65\x72\x5f\x6d\x73\x67\x5f\x74\0\x6d\x65\x73\x73\x61\x67\x65\0\x63\
\x68\x61\x72\0\x6d\x61\x78\x5f\x65\x6e\x74\x72\x69\x65\x73\0\x6b\x65\x79\0\x76\
\x61\x6c\x75\x65\0\x6d\x79\x5f\x63\x6f\x6e\x66\x69\x67\0\x70\x74\x5f\x72\x65\
\x67\x73\0\x6f\x72\x69\x67\x5f\x78\x30\0\x73\x79\x73\x63\x61\x6c\x6c\x6e\x6f\0\
\x75\x6e\x75\x73\x65\x64\x32\0\x73\x64\x65\x69\x5f\x74\x74\x62\x72\x31\0\x70\
\x6d\x72\x5f\x73\x61\x76\x65\0\x73\x74\x61\x63\x6b\x66\x72\x61\x6d\x65\0\x6c\
\x6f\x63\x6b\x64\x65\x70\x5f\x68\x61\x72\x64\x69\x72\x71\x73\0\x65\x78\x69\x74\
\x5f\x72\x63\x75\0\x75\x73\x65\x72\x5f\x72\x65\x67\x73\0\x75\x73\x65\x72\x5f\
\x70\x74\x5f\x72\x65\x67\x73\0\x72\x65\x67\x73\0\x73\x70\0\x70\x63\0\x70\x73\
\x74\x61\x74\x65\0\x5f\x5f\x75\x36\x34\0\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\
\x6c\x6f\x6e\x67\x20\x6c\x6f\x6e\x67\0\x75\x36\x34\0\x73\x33\x32\0\x5f\x5f\x73\
\x33\x32\0\x63\x74\x78\0\x68\x65\x6c\x6c\x6f\0\x6b\x73\x79\x73\x63\x61\x6c\x6c\
\x2f\x65\x78\x65\x63\x76\x65\0\x2f\x68\x6f\x6d\x65\x2f\x79\x69\x6a\x69\x2f\x6f\
\x70\x65\x6e\x73\x6f\x75\x72\x63\x65\x2f\x65\x62\x70\x66\x2d\x74\x6f\x6f\x6c\
\x73\x2f\x63\x68\x61\x70\x35\x2f\x68\x65\x6c\x6c\x6f\x2d\x62\x75\x66\x66\x65\
\x72\x2d\x63\x6f\x6e\x66\x69\x67\x2e\x62\x70\x66\x2e\x63\0\x69\x6e\x74\x20\x42\
\x50\x46\x5f\x4b\x50\x52\x4f\x42\x45\x5f\x53\x59\x53\x43\x41\x4c\x4c\x28\x68\
\x65\x6c\x6c\x6f\x2c\x20\x63\x6f\x6e\x73\x74\x20\x63\x68\x61\x72\x20\x2a\x70\
\x61\x74\x68\x29\x20\x7b\0\x30\x3a\x30\x3a\x30\0\x70\x74\x5f\x72\x65\x67\x73\
\x5f\x5f\x5f\x61\x72\x6d\x36\x34\0\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x6c\x6f\
\x6e\x67\0\x30\x3a\x30\0\x20\x20\x20\x20\x73\x74\x72\x75\x63\x74\x20\x64\x61\
\x74\x61\x5f\x74\x20\x64\x61\x74\x61\x20\x3d\x20\x7b\x7d\x3b\0\x20\x20\x20\x20\
\x64\x61\x74\x61\x2e\x70\x69\x64\x20\x3d\x20\x62\x70\x66\x5f\x67\x65\x74\x5f\
\x63\x75\x72\x72\x65\x6e\x74\x5f\x70\x69\x64\x5f\x74\x67\x69\x64\x28\x29\x20\
\x3e\x3e\x20\x33\x32\x3b\0\x20\x20\x20\x20\x64\x61\x74\x61\x2e\x75\x69\x64\x20\
\x3d\x20\x62\x70\x66\x5f\x67\x65\x74\x5f\x63\x75\x72\x72\x65\x6e\x74\x5f\x75\
\x69\x64\x5f\x67\x69\x64\x28\x29\x20\x26\x20\x30\x78\x46\x46\x46\x46\x46\x46\
\x46\x46\x3b\0\x20\x20\x20\x20\x62\x70\x66\x5f\x67\x65\x74\x5f\x63\x75\x72\x72\
\x65\x6e\x74\x5f\x63\x6f\x6d\x6d\x28\x26\x64\x61\x74\x61\x2e\x63\x6f\x6d\x6d\
\x61\x6e\x64\x2c\x20\x73\x69\x7a\x65\x6f\x66\x28\x64\x61\x74\x61\x2e\x63\x6f\
\x6d\x6d\x61\x6e\x64\x29\x29\x3b\0\x20\x20\x20\x20\x62\x70\x66\x5f\x70\x72\x6f\
\x62\x65\x5f\x72\x65\x61\x64\x5f\x75\x73\x65\x72\x5f\x73\x74\x72\x28\x26\x64\
\x61\x74\x61\x2e\x70\x61\x74\x68\x2c\x20\x73\x69\x7a\x65\x6f\x66\x28\x64\x61\
\x74\x61\x2e\x70\x61\x74\x68\x29\x2c\x20\x70\x61\x74\x68\x29\x3b\0\x20\x20\x20\
\x20\x70\x20\x3d\x20\x62\x70\x66\x5f\x6d\x61\x70\x5f\x6c\x6f\x6f\x6b\x75\x70\
\x5f\x65\x6c\x65\x6d\x28\x26\x6d\x79\x5f\x63\x6f\x6e\x66\x69\x67\x2c\x20\x26\
\x64\x61\x74\x61\x2e\x75\x69\x64\x29\x3b\0\x20\x20\x20\x20\x62\x70\x66\x5f\x70\
\x65\x72\x66\x5f\x65\x76\x65\x6e\x74\x5f\x6f\x75\x74\x70\x75\x74\x28\x63\x74\
\x78\x2c\x20\x26\x6f\x75\x74\x70\x75\x74\x2c\x20\x42\x50\x46\x5f\x46\x5f\x43\
\x55\x52\x52\x45\x4e\x54\x5f\x43\x50\x55\x2c\x20\x26\x64\x61\x74\x61\x2c\x20\
\x73\x69\x7a\x65\x6f\x66\x28\x64\x61\x74\x61\x29\x29\x3b\0\x5f\x42\x6f\x6f\x6c\
\0\x4c\x49\x4e\x55\x58\x5f\x48\x41\x53\x5f\x53\x59\x53\x43\x41\x4c\x4c\x5f\x57\
\x52\x41\x50\x50\x45\x52\0\x4c\x49\x43\x45\x4e\x53\x45\0\x2e\x64\x61\x74\x61\0\
\x2e\x6b\x63\x6f\x6e\x66\x69\x67\0\x2e\x6d\x61\x70\x73\0\x6c\x69\x63\x65\x6e\
\x73\x65\0\x9f\xeb\x01\0\x20\0\0\0\0\0\0\0\x14\0\0\0\x14\0\0\0\x4c\x02\0\0\x60\
\x02\0\0\x3c\0\0\0\x08\0\0\0\x3d\x01\0\0\x01\0\0\0\0\0\0\0\x23\0\0\0\x10\0\0\0\
\x3d\x01\0\0\x24\0\0\0\0\0\0\0\x4d\x01\0\0\x8e\x01\0\0\0\x70\0\0\x08\0\0\0\x4d\
\x01\0\0\x8e\x01\0\0\x05\x70\0\0\x50\0\0\0\x4d\x01\0\0\x8e\x01\0\0\x05\x70\0\0\
\x60\0\0\0\x4d\x01\0\0\x8e\x01\0\0\x05\x70\0\0\x70\0\0\0\x4d\x01\0\0\xe8\x01\0\
\0\x13\x74\0\0\xc8\0\0\0\x4d\x01\0\0\x05\x02\0\0\x10\x80\0\0\xd0\0\0\0\x4d\x01\
\0\0\x05\x02\0\0\x2b\x80\0\0\xd8\0\0\0\x4d\x01\0\0\x05\x02\0\0\x0e\x80\0\0\xe0\
\0\0\0\x4d\x01\0\0\x36\x02\0\0\x10\x84\0\0\xe8\0\0\0\x4d\x01\0\0\x36\x02\0\0\
\x0e\x84\0\0\xf0\0\0\0\x4d\x01\0\0\xe8\x01\0\0\x13\x74\0\0\0\x01\0\0\x4d\x01\0\
\0\x6d\x02\0\0\x05\x8c\0\0\x10\x01\0\0\x4d\x01\0\0\xe8\x01\0\0\x13\x74\0\0\x20\
\x01\0\0\x4d\x01\0\0\xac\x02\0\0\x05\x90\0\0\x38\x01\0\0\x4d\x01\0\0\x36\x02\0\
\0\x0a\x84\0\0\x48\x01\0\0\x4d\x01\0\0\xee\x02\0\0\x09\x98\0\0\xa0\x01\0\0\x4d\
\x01\0\0\0\0\0\0\0\0\0\0\xa8\x01\0\0\x4d\x01\0\0\x8e\x01\0\0\x05\x70\0\0\xb8\
\x01\0\0\x4d\x01\0\0\x8e\x01\0\0\x05\x70\0\0\xc8\x01\0\0\x4d\x01\0\0\xe8\x01\0\
\0\x13\x74\0\0\x20\x02\0\0\x4d\x01\0\0\x05\x02\0\0\x10\x80\0\0\x28\x02\0\0\x4d\
\x01\0\0\x05\x02\0\0\x2b\x80\0\0\x30\x02\0\0\x4d\x01\0\0\x05\x02\0\0\x0e\x80\0\
\0\x38\x02\0\0\x4d\x01\0\0\x36\x02\0\0\x10\x84\0\0\x40\x02\0\0\x4d\x01\0\0\x36\
\x02\0\0\x0e\x84\0\0\x48\x02\0\0\x4d\x01\0\0\xe8\x01\0\0\x13\x74\0\0\x58\x02\0\
\0\x4d\x01\0\0\x6d\x02\0\0\x05\x8c\0\0\x68\x02\0\0\x4d\x01\0\0\xe8\x01\0\0\x13\
\x74\0\0\x78\x02\0\0\x4d\x01\0\0\xac\x02\0\0\x05\x90\0\0\x90\x02\0\0\x4d\x01\0\
\0\x36\x02\0\0\x0a\x84\0\0\xa0\x02\0\0\x4d\x01\0\0\xee\x02\0\0\x09\x98\0\0\xd8\
\x02\0\0\x4d\x01\0\0\xe8\x01\0\0\x13\x74\0\0\xe8\x02\0\0\x4d\x01\0\0\0\0\0\0\0\
\0\0\0\0\x03\0\0\x4d\x01\0\0\xe8\x01\0\0\x13\x74\0\0\x08\x03\0\0\x4d\x01\0\0\
\x22\x03\0\0\x05\xb4\0\0\x40\x03\0\0\x4d\x01\0\0\x8e\x01\0\0\x05\x70\0\0\x10\0\
\0\0\x3d\x01\0\0\x03\0\0\0\x28\0\0\0\x18\0\0\0\xc0\x01\0\0\0\0\0\0\x30\0\0\0\
\x24\0\0\0\xe4\x01\0\0\0\0\0\0\x80\x01\0\0\x24\0\0\0\xe4\x01\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x03\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\xb2\0\0\0\0\0\x03\0\x80\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xa4\0\
\0\0\0\0\x03\0\xd8\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xab\0\0\0\0\0\x03\0\xd0\x02\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x21\0\0\0\x12\0\x03\0\0\0\0\0\0\0\0\0\x50\x03\0\0\
\0\0\0\0\x79\0\0\0\x10\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x35\0\0\0\x11\0\
\x07\0\x18\0\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\x5b\0\0\0\x11\0\x05\0\0\0\0\0\0\0\0\
\0\x0c\0\0\0\0\0\0\0\x14\0\0\0\x11\0\x07\0\0\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0\
\x9c\0\0\0\x11\0\x06\0\0\0\0\0\0\0\0\0\x0d\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\x01\
\0\0\0\x06\0\0\0\x48\x01\0\0\0\0\0\0\x01\0\0\0\x07\0\0\0\x60\x01\0\0\0\0\0\0\
\x01\0\0\0\x08\0\0\0\xa0\x02\0\0\0\0\0\0\x01\0\0\0\x07\0\0\0\xb8\x02\0\0\0\0\0\
\0\x01\0\0\0\x08\0\0\0\x10\x03\0\0\0\0\0\0\x01\0\0\0\x09\0\0\0\x08\x04\0\0\0\0\
\0\0\x04\0\0\0\x08\0\0\0\x20\x04\0\0\0\0\0\0\x03\0\0\0\x06\0\0\0\x38\x04\0\0\0\
\0\0\0\x04\0\0\0\x09\0\0\0\x44\x04\0\0\0\0\0\0\x04\0\0\0\x07\0\0\0\x5c\x04\0\0\
\0\0\0\0\x04\0\0\0\x0a\0\0\0\x2c\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x40\0\0\0\0\
\0\0\0\x04\0\0\0\x01\0\0\0\x50\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x60\0\0\0\0\0\
\0\0\x04\0\0\0\x01\0\0\0\x70\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x80\0\0\0\0\0\0\
\0\x04\0\0\0\x01\0\0\0\x90\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xa0\0\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\xb0\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xc0\0\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\xd0\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xe0\0\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\xf0\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\0\x01\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\x10\x01\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x20\x01\0\0\0\0\0\
\0\x04\0\0\0\x01\0\0\0\x30\x01\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x40\x01\0\0\0\0\
\0\0\x04\0\0\0\x01\0\0\0\x50\x01\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x60\x01\0\0\0\
\0\0\0\x04\0\0\0\x01\0\0\0\x70\x01\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x80\x01\0\0\
\0\0\0\0\x04\0\0\0\x01\0\0\0\x90\x01\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xa0\x01\0\
\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xb0\x01\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xc0\x01\
\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xd0\x01\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xe0\
\x01\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xf0\x01\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\0\
\x02\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x10\x02\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\
\x20\x02\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x30\x02\0\0\0\0\0\0\x04\0\0\0\x01\0\0\
\0\x40\x02\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x50\x02\0\0\0\0\0\0\x04\0\0\0\x01\0\
\0\0\x60\x02\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x70\x02\0\0\0\0\0\0\x04\0\0\0\x01\
\0\0\0\x8c\x02\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x9c\x02\0\0\0\0\0\0\x04\0\0\0\
\x01\0\0\0\xac\x02\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x0e\x11\x13\x12\x10\0\x2e\
\x74\x65\x78\x74\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\x2e\x65\x78\x74\0\x6f\x75\
\x74\x70\x75\x74\0\x2e\x6d\x61\x70\x73\0\x68\x65\x6c\x6c\x6f\0\x2e\x6c\x6c\x76\
\x6d\x5f\x61\x64\x64\x72\x73\x69\x67\0\x6d\x79\x5f\x63\x6f\x6e\x66\x69\x67\0\
\x2e\x72\x65\x6c\x6b\x73\x79\x73\x63\x61\x6c\x6c\x2f\x65\x78\x65\x63\x76\x65\0\
\x6c\x69\x63\x65\x6e\x73\x65\0\x6d\x65\x73\x73\x61\x67\x65\0\x2e\x73\x74\x72\
\x74\x61\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\x2e\x64\x61\x74\x61\0\x4c\x49\x4e\
\x55\x58\x5f\x48\x41\x53\x5f\x53\x59\x53\x43\x41\x4c\x4c\x5f\x57\x52\x41\x50\
\x50\x45\x52\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\0\x4c\x49\x43\x45\x4e\x53\x45\0\
\x4c\x42\x42\x30\x5f\x35\0\x4c\x42\x42\x30\x5f\x34\0\x4c\x42\x42\x30\x5f\x33\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x63\0\0\0\x03\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xfd\x12\0\0\0\0\0\0\xb9\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x43\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\
\0\0\0\0\0\0\0\x50\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x3f\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xc8\x0f\0\0\0\0\0\
\0\x60\0\0\0\0\0\0\0\x0d\0\0\0\x03\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\
\x73\0\0\0\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x90\x03\0\0\0\0\0\0\x0c\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x53\0\0\0\x01\
\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x9c\x03\0\0\0\0\0\0\x0d\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1b\0\0\0\x01\0\0\0\x03\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\xb0\x03\0\0\0\0\0\0\x38\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x97\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\xe8\x03\0\0\0\0\0\0\x1c\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x93\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x28\x10\0\0\0\0\0\0\x50\0\0\0\0\0\0\0\x0d\0\0\0\x08\0\0\0\x08\0\0\0\0\0\0\0\
\x10\0\0\0\0\0\0\0\x0b\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\x0c\
\0\0\0\0\0\0\xbc\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\x07\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x78\x10\0\0\0\0\0\0\
\x80\x02\0\0\0\0\0\0\x0d\0\0\0\x0a\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\
\x27\0\0\0\x03\x4c\xff\x6f\0\0\0\x80\0\0\0\0\0\0\0\0\0\0\0\0\xf8\x12\0\0\0\0\0\
\0\x05\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x6b\0\0\
\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xc0\x0e\0\0\0\0\0\0\x08\x01\0\0\0\
\0\0\0\x01\0\0\0\x05\0\0\0\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0";

	*sz = sizeof(data) - 1;
	return (const void *)data;
}

#ifdef __cplusplus
struct hello_buffer_config_bpf *hello_buffer_config_bpf::open(const struct bpf_object_open_opts *opts) { return hello_buffer_config_bpf__open_opts(opts); }
struct hello_buffer_config_bpf *hello_buffer_config_bpf::open_and_load() { return hello_buffer_config_bpf__open_and_load(); }
int hello_buffer_config_bpf::load(struct hello_buffer_config_bpf *skel) { return hello_buffer_config_bpf__load(skel); }
int hello_buffer_config_bpf::attach(struct hello_buffer_config_bpf *skel) { return hello_buffer_config_bpf__attach(skel); }
void hello_buffer_config_bpf::detach(struct hello_buffer_config_bpf *skel) { hello_buffer_config_bpf__detach(skel); }
void hello_buffer_config_bpf::destroy(struct hello_buffer_config_bpf *skel) { hello_buffer_config_bpf__destroy(skel); }
const void *hello_buffer_config_bpf::elf_bytes(size_t *sz) { return hello_buffer_config_bpf__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
hello_buffer_config_bpf__assert(struct hello_buffer_config_bpf *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
	_Static_assert(sizeof(s->data->message) == 12, "unexpected size of 'message'");
	_Static_assert(sizeof(s->kconfig->LINUX_HAS_SYSCALL_WRAPPER) == 1, "unexpected size of 'LINUX_HAS_SYSCALL_WRAPPER'");
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __HELLO_BUFFER_CONFIG_BPF_SKEL_H__ */
